version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
    timezone: Australia/Sydney
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: mongodb
    versions:
    - 3.6.3
    - 3.6.4
    - 3.6.5
  - dependency-name: bson
    versions:
    - 4.2.2
    - 4.2.3
  - dependency-name: mocha
    versions:
    - 8.3.1
  - dependency-name: debug
    versions:
    - 4.3.1
  - dependency-name: ms
    versions:
    - 2.1.3
  - dependency-name: yargs
    versions:
    - 16.2.0
  - dependency-name: lodash
    versions:
    - 4.17.19
  - dependency-name: async
    versions:
    - 3.2.0
  - dependency-name: js-yaml
    versions:
    - 4.0.0
  - dependency-name: ini
    versions:
    - 1.3.8
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: coveralls
    versions:
    - 3.1.0
  - dependency-name: acorn
    versions:
    - 5.7.4
