name: unit tests

on:
  pull_request:
    branches:
      - master

jobs:
  unitTest:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: bahmutov/npm-install@v1
      - run: npm test
      - run: npm run coverage 
 # Maybe we should add https://github.com/marketplace/actions/gitter-notify here?